apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/ryandawsonuk/activiti-rb-app:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/ryandawsonuk/activiti-rb-app:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: activiti-rb-app
        chartPath: charts/activiti-rb-app
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/ryandawsonuk/activiti-rb-app'
          image.tag: '{{.DIGEST_HEX}}'
